// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParseContabil.Infrastructure.Context;

#nullable disable

namespace ParseContabil.Infrastructure.Migrations
{
    [DbContext(typeof(ParseContabilContext))]
    [Migration("20241112231323_fixErrorTemplate")]
    partial class fixErrorTemplate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ParseContabil.Domain.Entities.ProcessTaskLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("ProcessTaskLogs", (string)null);
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.RecordType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileOutPutName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionType")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("RecordTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Description = "Alta de Apuntes sin IVA",
                            FileOutPutName = "AltaApuntesIva",
                            PositionType = 0,
                            Type = "0"
                        },
                        new
                        {
                            Id = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Description = "Alta Cabecera de apuntes con IVA (Formato para Facturas)",
                            FileOutPutName = "AltaCabeceraApuntesConIva",
                            PositionType = 0,
                            Type = "1"
                        },
                        new
                        {
                            Id = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Description = "Detalle de apuntes con IVA (Facturas y rectificativas)",
                            FileOutPutName = "DetalleApuntesConIva",
                            PositionType = 0,
                            Type = "9"
                        },
                        new
                        {
                            Id = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Description = "Alta y modificación de cuentas y/o clientes o proveedores",
                            FileOutPutName = "AltaModificacionCuentas",
                            PositionType = 0,
                            Type = "C"
                        });
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RecordTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("TypeData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecordTypeId");

                    b.ToTable("Templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("81db4d2a-795b-46f7-9f85-fd31c14c66c8"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("57117d82-9c55-4a7e-81f9-50596e9934c4"),
                            Head = "Codigo de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("35034ac2-f262-45e7-a420-8c88fd2ab561"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("a184a93c-d4aa-4dae-845a-c4bf59456cb1"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ad8cf9a3-4fef-4b82-a2a8-ee21cc71f36b"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("cd5184c3-066e-4315-a9c6-b341b92058e3"),
                            Head = "Descripcion de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7e4f876a-3409-4510-ba1a-602f9b99feb3"),
                            Head = "Tipo de importe",
                            Order = 7,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f087d364-07e4-464c-91aa-9cbb5d0cece0"),
                            Head = "Referencia del documento",
                            Order = 8,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("9217c7a4-91ea-4db5-916d-69d9f658cdd3"),
                            Head = "Linea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f7e6e2b7-2f27-4bee-b8ba-c7ef9318c218"),
                            Head = "Descripcion del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("6f05811f-bc45-48c3-a8fa-f9b97ec3dbf9"),
                            Head = "Importe",
                            Order = 11,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("048d3bc6-541e-41f1-a195-ec72364179c6"),
                            Head = "Reserva",
                            Order = 12,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 137,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b8d83103-4a4f-4cc0-9674-a2af103f10fe"),
                            Head = "Indicador de Asiento de nomina",
                            Order = 13,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("2ea64923-c68a-44e0-96c4-d4ac95501a32"),
                            Head = "Tiene Registro Analitico",
                            Order = 14,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("47d87b98-e502-43aa-abe0-e06f8af4e3cb"),
                            Head = "Reserva",
                            Order = 15,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 256,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("fe3983d9-11c1-4739-8f6b-58ac99d00dc7"),
                            Head = "Moneda enlace",
                            Order = 16,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("645ab8cc-981f-4c6b-9bfb-ca46235f6c38"),
                            Head = "Indicador de generado",
                            Order = 17,
                            RecordTypeId = new Guid("fe47f840-d881-4901-835a-9ff968a7bc9e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("c9691162-e090-48ee-a30e-24325de19919"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("0440208c-2f49-47ce-bd8a-662062b07646"),
                            Head = "Codigo de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("6ffb1144-9e60-4287-8174-d5f3a47f5c69"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("177b8d10-b326-4169-96de-10119aea608a"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("0f9f06ef-c296-40a2-a7a1-869c76bd8e5b"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("a7becb8e-c942-4e17-a939-4420fdbee03d"),
                            Head = "Descripcion de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("22dbb753-73e9-4c80-8baa-7bcd06dd12d2"),
                            Head = "Tipo de factura",
                            Order = 7,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("228d1630-02fa-4bd1-9b99-2baf5569cdbf"),
                            Head = "Numero de factura o documento",
                            Order = 8,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("552f5b08-5c55-46e7-9263-f3f41acf628b"),
                            Head = "Linea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("5718875d-e3d7-406d-8d21-c8b6c4d0d6e8"),
                            Head = "Descripcion del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("cef87c7c-21bc-46b0-8ea0-5807d388f7ef"),
                            Head = "Importe",
                            Order = 11,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("dffb4408-b940-4767-991e-c2618defb9fa"),
                            Head = "Reserva",
                            Order = 12,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 62,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("cc18da39-52c1-446a-b240-b807f20f7c5e"),
                            Head = "NIF cliente o proveedor",
                            Order = 13,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("0ff42e35-f158-4e58-8ecb-b9cb364ed6fc"),
                            Head = "Nombre cliente o proveedor",
                            Order = 14,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 40,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("9e5711c6-6076-4aa3-a495-f0635201ea74"),
                            Head = "Codigo postal",
                            Order = 15,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("68b4f9db-2c8e-4acd-a6f4-308f80250cc3"),
                            Head = "Reserva",
                            Order = 16,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f6b35d53-c834-44aa-b2b9-bf64fa357c90"),
                            Head = "Fecha de operacion",
                            Order = 17,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("46347fe7-979c-4edc-bc6b-b4f8ed522904"),
                            Head = "Fecha de factura",
                            Order = 18,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("cee7ba57-6f31-4df0-a384-ee47c3576b9c"),
                            Head = "Numero factura ampliado para el SII",
                            Order = 19,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 60,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b93860b1-9788-4109-8b8f-33e3a4554370"),
                            Head = "reserva",
                            Order = 20,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 196,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7db56bd8-5442-43e7-be5a-5a567095dc50"),
                            Head = "Moneda enlace",
                            Order = 21,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7f1e4622-0a6b-451f-9170-d34e11d751af"),
                            Head = "Indicador de generado",
                            Order = 22,
                            RecordTypeId = new Guid("5b7ea064-0da5-48a9-a29a-85c4ef2d9023"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("1eefb66c-28a9-474e-ad0e-665ca40da9e0"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("0cf568f3-4ea9-4634-b60c-7d46fe9724cb"),
                            Head = "Codigo de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("2aa9ab0c-0d3c-4f79-a11e-dc59cba50e82"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("1269b01b-fc65-4814-8bd5-eae6248b2c63"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("52b5340f-4151-4f55-ad15-0aae456dcc7d"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b465aece-2b24-4726-863a-adec3e1a5723"),
                            Head = "Descripcion de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("343e5d99-31a5-4e76-8638-530ca642476b"),
                            Head = "Tipo de importe",
                            Order = 7,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("46bf2c64-fbf8-4391-9f40-180552e4c52b"),
                            Head = "Número de factura o documento",
                            Order = 8,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("80182c82-0eb0-48ca-9590-8a8447b5840e"),
                            Head = "Linea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ffaa74bd-60b7-4716-91b3-c741e150cdc4"),
                            Head = "Descripcion del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("4f9ec810-a358-474f-b563-2addcdfdd130"),
                            Head = "Subtipo de factura",
                            Order = 11,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("8df72ed0-2dbb-460b-bdad-a597c2d1c738"),
                            Head = "Base imponible",
                            Order = 12,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("9c9bb9f9-6968-47cb-8e7f-7d045247b7d3"),
                            Head = "Porcentaje de IVA",
                            Order = 13,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 5,
                            TypeData = "decimal"
                        },
                        new
                        {
                            Id = new Guid("7fcb123a-f7f3-47db-9bd5-0beddd8653c7"),
                            Head = "Cuota de IVA",
                            Order = 14,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("a0e65663-3525-4f76-b13d-33e602b6ed15"),
                            Head = "Porcentaje de Recargo",
                            Order = 15,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7f1eb0c9-8673-4343-889b-dc0e5e849650"),
                            Head = "Cuota de Recargo",
                            Order = 16,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("e5249316-a2fa-4066-b497-48c24d7d492d"),
                            Head = "Porcentaje de Retencion",
                            Order = 17,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 5,
                            TypeData = "decimal"
                        },
                        new
                        {
                            Id = new Guid("e25d54e3-1b89-47a6-87f4-9f4dba6d195a"),
                            Head = "Cuota de Retencion",
                            Order = 18,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("536f70ad-3175-412f-bdc5-ba7ed5d2d616"),
                            Head = "error template",
                            Order = 19,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ed250083-600d-4362-bb8a-e387873ab364"),
                            Head = "Operacion sujeta a IVA",
                            Order = 20,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("aa27f9b0-efaf-41be-bb01-7fa3c15efd34"),
                            Head = "Marca afecta 415",
                            Order = 21,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("5e9d1440-e057-43e2-a8e9-5c51646c34a1"),
                            Head = "Marca factura en criterio de caja",
                            Order = 22,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7b5394d1-cfb1-401b-9c65-c9ce8d72d604"),
                            Head = "reserva",
                            Order = 23,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("e7edd0ac-c95f-474a-a502-068097b5a7fc"),
                            Head = "Cuenta de IVA Soportado",
                            Order = 24,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("9ef06d64-ef24-4848-81f1-df82af479d7c"),
                            Head = "Cuenta de recargo Soportado",
                            Order = 25,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("59d143cf-3bd1-4f30-8706-d2a5a28c2b25"),
                            Head = "Cuenta de retencion",
                            Order = 26,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ce95da46-9b96-497a-8f90-e5f2c5dced2f"),
                            Head = "Cuenta de IVA 2 Repercutido",
                            Order = 27,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("a2612cc8-5f7c-49d8-8637-468b6f92a760"),
                            Head = "Cuenta de recargo 2 Repercutid",
                            Order = 28,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("713ac8c1-64da-431b-9cc0-f8cd291dd755"),
                            Head = "Tiene Registro Analitico",
                            Order = 29,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("dd4ab0dc-c4ec-494a-b52f-f70156663b45"),
                            Head = "reserva",
                            Order = 30,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 256,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("afd2598c-cab0-4c41-95bb-68014a753bce"),
                            Head = "Moneda enlace",
                            Order = 31,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ca33fc46-03c7-4f1a-8c84-25ff34699b08"),
                            Head = "Indicador de generado",
                            Order = 32,
                            RecordTypeId = new Guid("2c3f6156-46ce-4c2c-b89a-4b380bc3f826"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("6d63addc-ae65-4a9f-821a-f4f8ebb0ddb1"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("da9ba112-5ef6-4cf1-8e80-005a9f4dfb38"),
                            Head = "Codigo de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("82071da4-6d1e-4873-9fc0-1068e1b3fd9f"),
                            Head = "Fecha del alta",
                            Order = 3,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("ca297fc7-62be-4569-bb69-c8c03972a154"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("fea1809c-b386-478c-90a4-c21c16eb6511"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("19bbf82e-f8be-41cf-bc96-a01db5a34f06"),
                            Head = "Actualizar Saldo Inicial",
                            Order = 6,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("3acec59d-64f9-438f-9178-dd17a9e940af"),
                            Head = "Actualizar Saldo Inicial",
                            Order = 7,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("5a5e3d6f-c781-469e-ae61-1a2ee8901347"),
                            Head = "Saldo Inicial",
                            Order = 8,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("4acba5e1-247d-4f5a-8cca-a7f918b3a3c8"),
                            Head = "Ampliacion",
                            Order = 9,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("90d5a338-3400-4982-a2db-cc9bd35ade80"),
                            Head = "reserva",
                            Order = 10,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 4,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ff0649c7-65b8-46b2-969d-bc06268e73f7"),
                            Head = "NIF",
                            Order = 11,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("553386b0-4f2e-440b-a759-37fc4f19e2f7"),
                            Head = "Siglas Vía Publica",
                            Order = 12,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("08df0208-fbb8-4f59-8494-1554df4bfad3"),
                            Head = "Via Publica",
                            Order = 13,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("416e0634-4953-4682-a39d-646ced096a92"),
                            Head = "Numero",
                            Order = 14,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b8d247d5-1e3c-46b4-bcfe-b67a258318a9"),
                            Head = "Escalera",
                            Order = 15,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("4e15afd3-8ea1-4f69-8eaf-1a7deab28861"),
                            Head = "Piso",
                            Order = 16,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("4b870192-d80b-4aea-b4ea-c5c113303bc7"),
                            Head = "Puerta",
                            Order = 17,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("26e4f0d6-f259-4812-8ead-e31f2887d6bb"),
                            Head = "Municipio",
                            Order = 18,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 20,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("62ff54b7-9f2a-4e53-92c1-2909f75d42a1"),
                            Head = "Codigo Postal",
                            Order = 19,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("6c738229-e854-4b5c-81af-4a7ae648cbad"),
                            Head = "Provincia",
                            Order = 20,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 15,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ef51ad7b-26ee-4e10-91a9-e698e89641a1"),
                            Head = "Pais",
                            Order = 21,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 3,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("200e81b6-fbb7-4672-ba43-d6b29cac68d9"),
                            Head = "Telefono",
                            Order = 22,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("684dc2aa-9cc3-4d6a-9607-5d6b9d504ba8"),
                            Head = "Extension",
                            Order = 23,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 4,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("79ac90e1-7938-4c5d-88d4-aab66b974329"),
                            Head = "Fax",
                            Order = 24,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("c791a9a2-e609-45a8-9068-ff6674208426"),
                            Head = "E-mail",
                            Order = 25,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("fa1f9bd3-4229-46a1-b863-daeb546f4d5c"),
                            Head = "Reservado",
                            Order = 26,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("3e1301b3-b148-401f-9bbe-3f71a60dccb4"),
                            Head = "Criterio de caja",
                            Order = 27,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("749a8990-aae4-4f05-afde-bc8eb7f701c0"),
                            Head = "Reservado",
                            Order = 28,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ea94991d-07d5-459b-948b-5b7a72d463a9"),
                            Head = "Cuenta contrapartida",
                            Order = 29,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("dae082e7-bd92-4a50-a671-5c75cbde6853"),
                            Head = "Codigo de pais",
                            Order = 30,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("382013ba-3009-4401-94d2-243194e9d851"),
                            Head = "reserva",
                            Order = 31,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 254,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("fb3a72e8-fd55-4ec3-acff-03919d5daa08"),
                            Head = "Moneda enlace",
                            Order = 32,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("3f2644a2-66ff-44bb-a7b2-93abb7ff5bb0"),
                            Head = "Indicador de generado",
                            Order = 33,
                            RecordTypeId = new Guid("d7e551f2-f279-4275-bf3d-a6e5b4f91448"),
                            Size = 1,
                            TypeData = "string"
                        });
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.Template", b =>
                {
                    b.HasOne("ParseContabil.Domain.Entities.RecordType", "RecordType")
                        .WithMany("Templates")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordType");
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.RecordType", b =>
                {
                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
