// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParseContabil.Infrastructure.Context;

#nullable disable

namespace ParseContabil.Infrastructure.Migrations
{
    [DbContext(typeof(ParseContabilContext))]
    [Migration("20241112175906_addData")]
    partial class addData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ParseContabil.Domain.Entities.RecordType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileOutPutName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionType")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("RecordTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Description = "Alta de Apuntes sin IVA",
                            FileOutPutName = "AltaApuntesIva",
                            PositionType = 0,
                            Type = "0"
                        },
                        new
                        {
                            Id = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Description = "Alta Cabecera de apuntes con IVA (Formato para Facturas)",
                            FileOutPutName = "AltaCabeceraApuntesConIva",
                            PositionType = 0,
                            Type = "1"
                        },
                        new
                        {
                            Id = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Description = "Detalle de apuntes con IVA (Facturas y rectificativas)",
                            FileOutPutName = "DetalleApuntesConIva",
                            PositionType = 0,
                            Type = "9"
                        },
                        new
                        {
                            Id = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Description = "Alta y modificación de cuentas y/o clientes o proveedores",
                            FileOutPutName = "AltaModificacionCuentas",
                            PositionType = 0,
                            Type = "C"
                        });
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RecordTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("TypeData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecordTypeId");

                    b.ToTable("Templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9726e40f-db46-4c98-ab8d-cdcdb09aef45"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("b35195ac-5d6c-429e-819c-5a620a24e9ba"),
                            Head = "Código de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("093680aa-5822-45c2-994b-9e4cf2571df7"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("7ceaa780-2299-4129-93c5-db2d97665acf"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("63929899-e3e6-45af-bf9e-3896fd0a05cf"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("cb2aa014-1ad8-4f9b-b9ad-bf1a85738f31"),
                            Head = "Descripción de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("597ea89e-15fa-4d2d-ad91-2245e3c3b3aa"),
                            Head = "Tipo de importe",
                            Order = 7,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("bdb53b41-7a53-4cd7-82e3-a2cec8a1fae8"),
                            Head = "Referencia del documento",
                            Order = 8,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f41d24ff-b96b-406b-9fc1-cb5e8eb7397a"),
                            Head = "Línea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("47d393f1-db68-424f-ba30-3594ea66cac4"),
                            Head = "Descripción del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("db536ac7-3aa7-47a0-bff2-3912ab11e63e"),
                            Head = "Importe",
                            Order = 11,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("bb5b9d81-2c3c-4a65-a838-58616ae61212"),
                            Head = "Reserva",
                            Order = 12,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 137,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("1e05744b-77d3-4a84-8421-18a0306c49dd"),
                            Head = "Indicador de Asiento de nómina",
                            Order = 13,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b4172b43-c8b1-4a9d-bef8-d3f634d958b5"),
                            Head = "Tiene Registro Analítico",
                            Order = 14,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("edf1f8e9-6c3a-4a73-bb98-9fb702d406a6"),
                            Head = "Reserva",
                            Order = 15,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 256,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("8af0dd84-c114-4c95-a55d-7071e15894d8"),
                            Head = "Moneda enlace",
                            Order = 16,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("d01fa2f7-4e5c-49c6-a25f-acab62a4f27e"),
                            Head = "Indicador de generado",
                            Order = 17,
                            RecordTypeId = new Guid("afd79133-a547-476b-bf1c-8fff019d8b65"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("111bc89a-feae-47c8-a2e1-d2a5a9f69abc"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("3b1b3199-e970-4cfb-a8e1-eb55de28b166"),
                            Head = "Código de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("85a7a435-9274-458c-81c4-a89cdb0d107c"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("4e0f481c-048c-49e7-b370-bcd1dbba2490"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("dee8df34-1949-4b03-b778-15394acc3545"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7f673eb7-3ae0-43ae-9b84-5427b6e6d839"),
                            Head = "Descripción de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("3fa7dea9-3523-48a9-b9e6-dc3a379ea9ce"),
                            Head = "Tipo de factura",
                            Order = 7,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7cf3dcba-9f34-4e76-a527-3ac9fb4eebfd"),
                            Head = "Número de factura o documento",
                            Order = 8,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("06ffbc85-859d-4c0f-8b3f-dd4cf646a915"),
                            Head = "Línea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("fc22808f-ff74-44e9-96b9-da6e3ef4087e"),
                            Head = "Descripción del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("d7a09426-45e8-4c33-9251-fc5a82658a39"),
                            Head = "Importe",
                            Order = 11,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("16d1c217-0bd4-4be7-be34-1b2e38a999b0"),
                            Head = "Reserva",
                            Order = 12,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 62,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("226385e5-ce7f-434f-910f-063a49a2966d"),
                            Head = "NIF cliente o proveedor",
                            Order = 13,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("760046b5-af4f-480d-8048-d599d21dbe7f"),
                            Head = "Nombre cliente o proveedor",
                            Order = 14,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 40,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("31c30e03-6a9c-4bda-8216-bbf46551df4a"),
                            Head = "Código postal",
                            Order = 15,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7985a466-15ef-406d-a5b5-ddab6c946e88"),
                            Head = "Reserva",
                            Order = 16,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("45951ac1-e766-452d-80d3-8f645328d4a9"),
                            Head = "Fecha de operación",
                            Order = 17,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("dd479f65-4ce4-4420-9d55-6ad2acdb053f"),
                            Head = "Fecha de factura",
                            Order = 18,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("a765b7fb-1229-496e-8f55-a20d9bfe2645"),
                            Head = "Número factura ampliado para el SII",
                            Order = 19,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 60,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7eca47e0-50c1-4d18-b3c2-eef4e839a910"),
                            Head = "reserva",
                            Order = 20,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 196,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ed81a2ae-e886-4ed5-b1b3-ad4952e1dd49"),
                            Head = "Moneda enlace",
                            Order = 21,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("bfe95d9d-c926-49c2-9c4a-1a438093af44"),
                            Head = "Indicador de generado",
                            Order = 22,
                            RecordTypeId = new Guid("821719bb-85c9-4d2b-91a8-aa9be9aad582"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("8ad94da2-502c-457e-8d3d-0b185c8476a7"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("6e37a529-f21a-4ccd-8aaa-aef92e028537"),
                            Head = "Código de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("8b0147ff-da57-494d-93af-961e30cfc087"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("80f3dce8-c22f-4dc1-a06c-e265324740dd"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("27ab0b48-f3f5-4401-bc8f-bcae769c0901"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("11198688-30d8-4743-bce0-0c3a36164748"),
                            Head = "Descripción de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("8e265aab-3db4-4ffb-a2f7-283a1565959b"),
                            Head = "Tipo de importe",
                            Order = 7,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("c90b0ee6-a783-4359-aa84-cbd7340de0ec"),
                            Head = "Número de factura o documento",
                            Order = 8,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("921637b8-9505-495d-bfa9-cb1850d4e393"),
                            Head = "Línea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("4087f9ab-ff5f-461e-a3a3-7733bd2656a2"),
                            Head = "Descripción del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("9708fdfb-c217-46ee-97c4-70cdb8e5b7e1"),
                            Head = "Subtipo de factura",
                            Order = 11,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("2bfcbf81-a8c7-4360-9d08-6890ad885b87"),
                            Head = "Base imponible",
                            Order = 12,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("3fe5907a-79b0-49fe-b20f-7c4cad3f7ce2"),
                            Head = "Porcentaje de IVA",
                            Order = 13,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 5,
                            TypeData = "decimal"
                        },
                        new
                        {
                            Id = new Guid("6fe8e3f1-e02d-41e6-aa0d-901834ccbd22"),
                            Head = "Cuota de IVA",
                            Order = 14,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("dc0dba32-cf83-47be-9666-25ea55bc45fd"),
                            Head = "Porcentaje de Recargo",
                            Order = 15,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("214a16b3-ac6f-4cbf-b68a-6660fc9959d2"),
                            Head = "Cuota de Recargo",
                            Order = 16,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7ac39cc8-c92e-4830-8c11-28e6c782f2d8"),
                            Head = "Porcentaje de Retención",
                            Order = 17,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 5,
                            TypeData = "decimal"
                        },
                        new
                        {
                            Id = new Guid("1154b4f8-a91b-42f0-8d1f-52dccd3e6cd9"),
                            Head = "Cuota de Retención",
                            Order = 18,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 14,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("927eaad1-39f2-4971-81c8-32c075f7a3e4"),
                            Head = "Operación sujeta a IVA",
                            Order = 19,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("8647a5f7-2a69-4de7-b0d9-965b4dae4fb2"),
                            Head = "Marca afecta 415",
                            Order = 20,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("47cbcf0f-443d-4b42-9c87-aa8ef58b24ac"),
                            Head = "Marca factura en criterio de caja",
                            Order = 21,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("77567665-6f1f-4c43-9f0f-c8219a18a20b"),
                            Head = "reserva",
                            Order = 22,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("1d02a8c2-b6a6-4633-b405-902a1d256d9b"),
                            Head = "Cuenta de IVA Soportado",
                            Order = 23,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("0c63e5c8-d56f-486d-ab1a-4c253a053546"),
                            Head = "Cuenta de recargo Soportado",
                            Order = 24,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("67cb94a5-9533-4515-8ebe-f3bf12c77c9a"),
                            Head = "Cuenta de retención",
                            Order = 25,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f4010a54-e895-4672-9306-e45c1272a8d2"),
                            Head = "Cuenta de IVA 2 Repercutido",
                            Order = 26,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("61813cf5-4425-40ac-8114-f386aba4b27d"),
                            Head = "Cuenta de recargo 2 Repercutid",
                            Order = 27,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("77716f25-17ae-4fb4-8f3e-54b6c5624af9"),
                            Head = "Tiene Registro Analítico",
                            Order = 28,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("1d0d3356-b08e-42b9-b84c-2d7e66f4f181"),
                            Head = "reserva",
                            Order = 29,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 256,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ad960616-866a-44eb-9d21-4df78dfd8d84"),
                            Head = "Moneda enlace",
                            Order = 30,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("234fe866-ab03-4062-808f-c5bc785d8a20"),
                            Head = "Indicador de generado",
                            Order = 31,
                            RecordTypeId = new Guid("f4dc644c-681a-4ff2-900a-4c0c033b8030"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("68a28b6f-4268-444d-b848-4b7ca3d269b0"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("23b2ac03-5e63-4dae-8945-5033d9e648b5"),
                            Head = "Código de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("73423762-8759-40e1-bb26-efb0d64a6b3c"),
                            Head = "Fecha del alta",
                            Order = 3,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("9c06d2fb-4bf4-47c6-a883-0db5664bc63a"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("27d00eab-d448-42ba-842c-92d0e062bfe7"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("1943dc4e-d469-488a-a803-3c433b2f4ec7"),
                            Head = "Actualizar Saldo Inicial",
                            Order = 6,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("91c985ab-96d2-463d-a093-32d7116bffba"),
                            Head = "Actualizar Saldo Inicial",
                            Order = 7,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("0a6bef3a-74aa-48d2-ab5d-c2e3d1094f4b"),
                            Head = "Saldo Inicial",
                            Order = 8,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("6b629ef4-565b-4130-888d-dcd787d473f6"),
                            Head = "Ampliación",
                            Order = 9,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("2ce012c3-dde9-49c2-9535-113eeeec32d4"),
                            Head = "reserva",
                            Order = 10,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 4,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("27d58ad7-bbb5-4f8b-8417-77f857550a8c"),
                            Head = "NIF",
                            Order = 11,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b6e4b283-a8ff-4e3e-8b57-5697ad1dfac8"),
                            Head = "Siglas Vía Publica",
                            Order = 12,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("1062f629-2663-434f-8ff6-5308fd1e2a93"),
                            Head = "Vía Publica",
                            Order = 13,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("de3f8b2e-827b-476d-b3f5-bd1584c661d5"),
                            Head = "Numero",
                            Order = 14,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("273f5b40-9313-4fec-b6eb-55d46e6f4a15"),
                            Head = "Escalera",
                            Order = 15,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("4269296d-dc98-4cfc-b2f6-eab257e045d6"),
                            Head = "Piso",
                            Order = 16,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("81259e98-64fc-480c-98f9-0195c06da237"),
                            Head = "Puerta",
                            Order = 17,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("3dd6e9fe-b0ce-406b-8c67-1f85d2c8b737"),
                            Head = "Municipio",
                            Order = 18,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 20,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b1d41dcf-444f-41eb-9032-a62ba25e02bc"),
                            Head = "Código Postal",
                            Order = 19,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("2125d18a-9cb2-4c12-bbf9-7d24fb313d81"),
                            Head = "Provincia",
                            Order = 20,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 15,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("36e1c68b-1120-44c7-8809-e62dc19a9e9d"),
                            Head = "Pais",
                            Order = 21,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 3,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f9d771fb-cb55-4017-a8b1-339a7b426245"),
                            Head = "Teléfono",
                            Order = 22,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f5ff3240-4dc4-471e-957d-6c1c7323adcf"),
                            Head = "Extensión",
                            Order = 23,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 4,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ab78558e-5dae-4edb-ad0b-ab71ef503dde"),
                            Head = "Fax",
                            Order = 24,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("febccc16-04c5-40cb-bbfd-0a58b8220756"),
                            Head = "E-mail",
                            Order = 25,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("65c7dbd7-28c6-4cbb-8f3c-1d6b384479b2"),
                            Head = "Reservado",
                            Order = 26,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("37e94c41-4275-4423-89db-5a0e7e68cd02"),
                            Head = "Criterio de caja",
                            Order = 27,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("0c66bd42-650b-426e-b652-7f64d874d612"),
                            Head = "Reservado",
                            Order = 28,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("383aec0b-86af-4df2-b68f-400661e0cfca"),
                            Head = "Cuenta contrapartida",
                            Order = 29,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("eab77874-1336-494b-a4bb-9eace0a656c6"),
                            Head = "Código de país",
                            Order = 30,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("819331de-ea9b-4fb1-8dcf-1e8d37458423"),
                            Head = "reserva",
                            Order = 31,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 254,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ed5cbb21-9fd1-444f-bebd-652ee4b04391"),
                            Head = "Moneda enlace",
                            Order = 32,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("6124f8c3-b010-4c5b-aea2-8b7ee64ed808"),
                            Head = "Indicador de generado",
                            Order = 33,
                            RecordTypeId = new Guid("333bac9c-af5b-44d0-9678-7f54bf78eeb9"),
                            Size = 1,
                            TypeData = "string"
                        });
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.Template", b =>
                {
                    b.HasOne("ParseContabil.Domain.Entities.RecordType", "RecordType")
                        .WithMany("Templates")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordType");
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.RecordType", b =>
                {
                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
