// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParseContabil.Infrastructure.Context;

#nullable disable

namespace ParseContabil.Infrastructure.Migrations
{
    [DbContext(typeof(ParseContabilContext))]
    partial class ParseContabilContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ParseContabil.Domain.Entities.ProcessTaskLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("ProcessTaskLogs", (string)null);
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.RecordType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileOutPutName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionType")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("RecordTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Description = "Alta de Apuntes sin IVA",
                            FileOutPutName = "AltaApuntesIva",
                            PositionType = 0,
                            Type = "0"
                        },
                        new
                        {
                            Id = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Description = "Alta Cabecera de apuntes con IVA (Formato para Facturas)",
                            FileOutPutName = "AltaCabeceraApuntesConIva",
                            PositionType = 0,
                            Type = "1"
                        },
                        new
                        {
                            Id = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Description = "Detalle de apuntes con IVA (Facturas y rectificativas)",
                            FileOutPutName = "DetalleApuntesConIva",
                            PositionType = 0,
                            Type = "9"
                        },
                        new
                        {
                            Id = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Description = "Alta y modificación de cuentas y/o clientes o proveedores",
                            FileOutPutName = "AltaModificacionCuentas",
                            PositionType = 0,
                            Type = "C"
                        });
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Head")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RecordTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("TypeData")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecordTypeId");

                    b.ToTable("Templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26c5759a-a546-41c5-9232-0a939ce9ee0c"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("341d6a98-2dfe-4995-821b-683f59fc7762"),
                            Head = "Código de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("82078b26-b118-4e28-b211-447459da9ec0"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("0e805f72-bbdc-495a-93d6-f77056eb2c38"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f57b1037-2c61-41b2-bb60-f87841aca9af"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("2618cabb-947b-46bc-bdf2-d64e7c2724de"),
                            Head = "Descripción de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("84ca3ca1-d9ae-4af1-889f-b77795ee2173"),
                            Head = "Tipo de importe",
                            Order = 7,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("49767817-8db8-46e6-8ce0-cd8cf3bbb7ab"),
                            Head = "Referencia del documento",
                            Order = 8,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("e7bd6498-279e-41b3-834a-08672588057f"),
                            Head = "Línea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("d8412031-940f-4e99-9100-733667720749"),
                            Head = "Descripción del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7ac27a80-e1d4-4df9-8a8e-556a18df6540"),
                            Head = "Importe",
                            Order = 11,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("784902dd-6ffa-4bcf-8d3e-acd54f245a1c"),
                            Head = "Reserva",
                            Order = 12,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 137,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ad724155-d987-4329-bf05-8768fc3b0dce"),
                            Head = "Indicador de Asiento de nómina",
                            Order = 13,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("fb7267c4-f0ee-49cc-99d8-d2fa5be20d1c"),
                            Head = "Tiene Registro Analítico",
                            Order = 14,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("53a3a020-1140-4e1c-9ff5-ec61fafef817"),
                            Head = "Reserva",
                            Order = 15,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 256,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("fab1fe0e-a4a2-4309-a16c-8a12d3f2ec56"),
                            Head = "Moneda enlace",
                            Order = 16,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("02e3f267-699d-4454-927c-20ee73436c24"),
                            Head = "Indicador de generado",
                            Order = 17,
                            RecordTypeId = new Guid("bddd3789-891f-4c12-ab7a-6b84916bf733"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("2c7f4fe6-cc2d-4a8d-80f0-0bab34cbf8a6"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("36a964c6-0b0d-4c61-a0ce-dded6c74caae"),
                            Head = "Código de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b30b456c-d19a-49b4-bbf5-610e0b3d5e31"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("8df094cd-8393-4c00-a03c-e942044fa93d"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("4740564d-5a5d-4112-a6d8-3dc9948d9ddd"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f2e25fbe-2332-4a89-8bd3-dd49a2275188"),
                            Head = "Descripción de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("5f816246-c675-44ec-891b-8fbf278c0158"),
                            Head = "Tipo de factura",
                            Order = 7,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("6a03d764-6d5f-4eb1-9132-c33a9664607a"),
                            Head = "Número de factura o documento",
                            Order = 8,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("4e094a3d-dbbf-45a2-98d8-c728dd5e29f8"),
                            Head = "Línea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("61f36698-9337-4e4e-bb99-c75400aa3b98"),
                            Head = "Descripción del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("bcd54d0b-2870-49b0-bd72-4b128326e5a0"),
                            Head = "Importe",
                            Order = 11,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("922a3234-c2cc-4216-a617-a1266d39b280"),
                            Head = "Reserva",
                            Order = 12,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 62,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("52b02751-423a-41b3-b71a-ffb250165271"),
                            Head = "NIF cliente o proveedor",
                            Order = 13,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("6a521c90-5bb7-401c-8a54-019c77b512ab"),
                            Head = "Nombre cliente o proveedor",
                            Order = 14,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 40,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("78617def-62c7-4336-9351-284282b55894"),
                            Head = "Código postal",
                            Order = 15,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("dbaaef72-6383-46a7-80fc-f333695c7a05"),
                            Head = "Reserva",
                            Order = 16,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("501070e6-0bb8-4a84-84cd-70d473606a9f"),
                            Head = "Fecha de operación",
                            Order = 17,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("5a28266f-f54c-44c9-b2c9-a355c8447c2e"),
                            Head = "Fecha de factura",
                            Order = 18,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("9c21ead6-863e-447d-bd3f-80252c8bcaa2"),
                            Head = "Número factura ampliado para el SII",
                            Order = 19,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 60,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("aa9fcbc4-eced-4064-b385-ab4898b7587b"),
                            Head = "reserva",
                            Order = 20,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 196,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("88216ca1-9874-4c18-8720-597598df7405"),
                            Head = "Moneda enlace",
                            Order = 21,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("3c8fb612-3904-4c50-9823-920ce2d19ab2"),
                            Head = "Indicador de generado",
                            Order = 22,
                            RecordTypeId = new Guid("5c4715ee-4979-4e3a-a7ff-6f5fc88826b2"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("904b33b7-2ef7-42fd-83de-a25ef0930f8b"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("bc65df4c-f9b4-4477-89bf-ee94a8d7e5ae"),
                            Head = "Código de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b7ea4f1d-a640-4c52-b783-d648816054bd"),
                            Head = "Fecha del apunte",
                            Order = 3,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("751f7a81-88ea-433e-9c9c-9c2341f493e2"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("1b386788-a39f-49de-bbc9-fb7b6300430f"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("44fe7899-2da1-4ddb-9f9d-19ab5e22a0d6"),
                            Head = "Descripción de la cuenta",
                            Order = 6,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("bbbc3619-62e9-4c1a-ba7a-d5194bc4bde4"),
                            Head = "Tipo de importe",
                            Order = 7,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("fc34e131-b762-4301-977c-6841bbd48b29"),
                            Head = "Número de factura o documento",
                            Order = 8,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 10,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("0b0d94e2-e130-4a54-9253-e79e3a1d52e8"),
                            Head = "Línea de apunte",
                            Order = 9,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("cae799f2-fef6-4553-85a1-48fcb84f5f47"),
                            Head = "Descripción del apunte",
                            Order = 10,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("7c39b39d-0344-421d-982a-0d3ab044bccd"),
                            Head = "Subtipo de factura",
                            Order = 11,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("be009425-4b7b-455e-8faf-18e6156f43e4"),
                            Head = "Base imponible",
                            Order = 12,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ffc65d0a-b43c-4187-bdfb-80a2712a374c"),
                            Head = "Porcentaje de IVA",
                            Order = 13,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 5,
                            TypeData = "decimal"
                        },
                        new
                        {
                            Id = new Guid("9f78f037-a624-4e00-b24a-d7d87c144abc"),
                            Head = "Cuota de IVA",
                            Order = 14,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("8369bed5-4d7a-444d-9fa8-944cc5f54b42"),
                            Head = "Porcentaje de Recargo",
                            Order = 15,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f0344879-21dc-4e6e-9ff9-41dab62c6013"),
                            Head = "Cuota de Recargo",
                            Order = 16,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("a6e5813f-8fba-48b5-9d71-6b5c71a79459"),
                            Head = "Porcentaje de Retención",
                            Order = 17,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 5,
                            TypeData = "decimal"
                        },
                        new
                        {
                            Id = new Guid("57189e63-7612-4c87-89a0-9b1379a8dfe7"),
                            Head = "Cuota de Retención",
                            Order = 18,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 14,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("410fdc8c-ce4b-4459-a202-9fe142093f7c"),
                            Head = "Operación sujeta a IVA",
                            Order = 19,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("67ec3f4b-44dd-43a7-89f7-0f6bdfd40cdf"),
                            Head = "Marca afecta 415",
                            Order = 20,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("681807b2-b83e-4498-9e16-0d6093d31f3a"),
                            Head = "Marca factura en criterio de caja",
                            Order = 21,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("e29cfd2c-344c-4006-8f55-abd81f231512"),
                            Head = "reserva",
                            Order = 22,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("0fd51513-614e-4b30-895b-e6a8c07ac218"),
                            Head = "Cuenta de IVA Soportado",
                            Order = 23,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("f4fda94b-167b-4e20-9fd4-4aeb5bbbd389"),
                            Head = "Cuenta de recargo Soportado",
                            Order = 24,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("a4c1b9be-6c7c-4420-b21a-bf15249321d7"),
                            Head = "Cuenta de retención",
                            Order = 25,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("71d66ab7-88a8-46b0-90b9-5cdb788c8223"),
                            Head = "Cuenta de IVA 2 Repercutido",
                            Order = 26,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("cedf157d-b9ed-41a3-a9a2-7ff2e8677766"),
                            Head = "Cuenta de recargo 2 Repercutid",
                            Order = 27,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("a016eeaa-af2a-491d-bd65-9142f17e971e"),
                            Head = "Tiene Registro Analítico",
                            Order = 28,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("35ea955d-fbf8-402d-b207-8de1bd05e366"),
                            Head = "reserva",
                            Order = 29,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 256,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("723ecfad-86b0-4f01-871c-b0c98baca753"),
                            Head = "Moneda enlace",
                            Order = 30,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("9443861d-b725-452b-9b6b-9cbd22c99add"),
                            Head = "Indicador de generado",
                            Order = 31,
                            RecordTypeId = new Guid("a25592d2-f360-47d6-b1bc-93aee9af2c0e"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b1e675fc-8610-42c6-87ba-fcb50f6caf28"),
                            Head = "Tipo de formato",
                            Order = 1,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 1,
                            TypeData = "int"
                        },
                        new
                        {
                            Id = new Guid("04516bb8-ba6b-4ee6-a56d-e26656609f7f"),
                            Head = "Código de empresa",
                            Order = 2,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("dfd39d2f-4ce0-4864-969e-540ada117792"),
                            Head = "Fecha del alta",
                            Order = 3,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 8,
                            TypeData = "date"
                        },
                        new
                        {
                            Id = new Guid("97946d16-5a4d-4ab2-b886-749197997ea9"),
                            Head = "Tipo de Registro",
                            Order = 4,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("da307d64-53df-4af2-b09d-50e3eb92c614"),
                            Head = "Cuenta",
                            Order = 5,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("69f2fdc3-753b-4afa-b37f-8d7027125c32"),
                            Head = "Actualizar Saldo Inicial",
                            Order = 6,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("36a0a18b-d05f-4f44-bb05-2b9d07119140"),
                            Head = "Actualizar Saldo Inicial",
                            Order = 7,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("1959150b-2ec7-4cb4-b448-d98daa0b8c7b"),
                            Head = "Saldo Inicial",
                            Order = 8,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("9418d059-e915-4660-beac-05e569757de8"),
                            Head = "Ampliación",
                            Order = 9,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b4a2335d-5082-4c00-80dc-aa6c1b4a5596"),
                            Head = "reserva",
                            Order = 10,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 4,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("591b1675-713b-4b2b-8b55-f75f69348da0"),
                            Head = "NIF",
                            Order = 11,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 14,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("d4e94de9-255b-4096-af62-5762e3a510ef"),
                            Head = "Siglas Vía Publica",
                            Order = 12,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("17e938cb-ef65-4cae-b848-42c593c72d5e"),
                            Head = "Vía Publica",
                            Order = 13,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b2014895-f680-477c-8e84-0cfa8f71bac4"),
                            Head = "Numero",
                            Order = 14,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("39af2975-80cc-4807-9040-2aa692fe11c9"),
                            Head = "Escalera",
                            Order = 15,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b7feb64e-471d-42b8-8f6c-3b0543a954e4"),
                            Head = "Piso",
                            Order = 16,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("d5f86f37-482c-47fa-8f88-6cb0990b1a1a"),
                            Head = "Puerta",
                            Order = 17,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("0bb46e3d-4d0c-48b7-a1d4-4c457dc72586"),
                            Head = "Municipio",
                            Order = 18,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 20,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b1faed6c-ff93-40e3-8f0a-e3eb12c78996"),
                            Head = "Código Postal",
                            Order = 19,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 5,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("75c5cfa3-4863-49d3-97ef-01a83859a634"),
                            Head = "Provincia",
                            Order = 20,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 15,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("195f46b2-8a39-4c42-86e5-1f29aa327d6f"),
                            Head = "Pais",
                            Order = 21,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 3,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("eb7c2da7-8ebc-4ab1-a77e-6629b82d5420"),
                            Head = "Teléfono",
                            Order = 22,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("166ae77f-22a5-43d4-981d-900f57b1fad2"),
                            Head = "Extensión",
                            Order = 23,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 4,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("18dab0b4-2102-45d2-8f51-ee7ba4a409bf"),
                            Head = "Fax",
                            Order = 24,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("16ef6279-5388-48d8-9620-8c2526060028"),
                            Head = "E-mail",
                            Order = 25,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 30,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("36989470-1b63-453f-823c-51583d7e9bbd"),
                            Head = "Reservado",
                            Order = 26,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("c6b8699d-e13a-45e2-a3cc-0865f1720908"),
                            Head = "Criterio de caja",
                            Order = 27,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("a9e6584e-db5c-4e1e-ab2a-24f2c9e518e6"),
                            Head = "Reservado",
                            Order = 28,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("8858d7d9-7b03-442e-a8ed-9bdc13897677"),
                            Head = "Cuenta contrapartida",
                            Order = 29,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 12,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("52734f15-b802-4650-9dd8-d3712b62f465"),
                            Head = "Código de país",
                            Order = 30,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 2,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("ef12c72c-4750-41da-a335-577f0c19d659"),
                            Head = "reserva",
                            Order = 31,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 254,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("25e69bce-c672-422b-b1bc-1454c0250eba"),
                            Head = "Moneda enlace",
                            Order = 32,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 1,
                            TypeData = "string"
                        },
                        new
                        {
                            Id = new Guid("b1a24917-55d8-461d-896b-8efb3fe8da6b"),
                            Head = "Indicador de generado",
                            Order = 33,
                            RecordTypeId = new Guid("4809da91-41bf-4de5-bd70-ffd9268cfb5f"),
                            Size = 1,
                            TypeData = "string"
                        });
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.Template", b =>
                {
                    b.HasOne("ParseContabil.Domain.Entities.RecordType", "RecordType")
                        .WithMany("Templates")
                        .HasForeignKey("RecordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordType");
                });

            modelBuilder.Entity("ParseContabil.Domain.Entities.RecordType", b =>
                {
                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
