//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseContabil.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParseContabil.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) generated.
        /// </summary>
        public static string CountFilesGenrated {
            get {
                return ResourceManager.GetString("CountFilesGenrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file of type :{0} not yet configured.
        /// </summary>
        public static string FileNotConfigured {
            get {
                return ResourceManager.GetString("FileNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing files end.
        /// </summary>
        public static string processingFileEnd {
            get {
                return ResourceManager.GetString("processingFileEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing files start.
        /// </summary>
        public static string processingFileStart {
            get {
                return ResourceManager.GetString("processingFileStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect line size, expect {0} and have {1}.
        /// </summary>
        public static string SizeLineError {
            get {
                return ResourceManager.GetString("SizeLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates of type :{0} not yet configured.
        /// </summary>
        public static string TemplateNotConfigured {
            get {
                return ResourceManager.GetString("TemplateNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify files End.
        /// </summary>
        public static string VerifyEnd {
            get {
                return ResourceManager.GetString("VerifyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify files start.
        /// </summary>
        public static string VerifyStart {
            get {
                return ResourceManager.GetString("VerifyStart", resourceCulture);
            }
        }
    }
}
